parameters:
  pdo.database: 'mvcc'
  pdo.config.required.fields: ['driver', 'host', 'port', 'dbname', 'username', 'password']

services:
  database.mvcc:
    class: PdoAdapter
    factory: ['@database.storage', getDatabase]
    arguments:
      - '%pdo.database%'
  connection.factory.pdo.trust:
    class: Vain\Pdo\Factory\PdoConnectionFactory
    arguments: ['pdo']
    tags:
      - {name: connection.factory}
  connection.factory.pdo.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    arguments: ['@connection.factory.pdo.trust', '%pdo.config.required.fields%']
  connection.factory.pdo: '@connection.factory.pdo.assert'
  database.factory.pdo:
    class: Vain\Pdo\Factory\PdoDatabaseFactory
    arguments: ['@database.generator.factory', 'pdo']
    tags:
      - {name: database.factory}