parameters:
  connection.pdo.name: 'mvcc'

services:
  database.pdo:
    parent: database.abstract
    class: Vain\Pdo\Database\PdoDatabase
    arguments: ['@connection.pdo']
  connection.pdo:
    parent: connection.abstract
    class: Vain\Pdo\Connection\PdoConnection
    arguments: ['%connection.pdo.name%']
    tags:
      - {name: connection}