services:
  database.pdo:
    parent: database.abstract
    class: Vain\Pdo\Database\PdoDatabase
  connection.factory.pdo:
    parent: connection.factory.abstract
    class: Vain\Pdo\Connection\Factory\PdoConnectionFactory
    tags:
      - {name: connection.factory}
  connection.factory.pdo.proxy:
    class: Vain\Core\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.factory.pdo
    decoration_priority: 100
    arguments: ['@connection.factory.pdo.proxy.inner']