imports:
  - { resource: '../di.yml' }

parameters:
  pdo.config.required.fields: ['type', 'host', 'port', 'dbname', 'username', 'password']

services:
  connection.factory.pdo.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    decorates: connection.factory.pdo
    decoration_priority: 900
    arguments: ['@connection.factory.pdo.assert.inner', '%pdo.config.required.fields%']
  connection.factory.pdo.logger:
    class: Vain\Connection\Factory\Decorator\Logger\ConnectionFactoryLoggerDecorator
    decorates: connection.factory.pdo
    decoration_priority: 1000
    arguments: ['@connection.factory.pdo.logger.inner', '@logger.connection']